# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Majesty Parish
email: solomonfaith53@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We are his majesty house parish based in zukoriko, kudenda, kaduna state, nigeria. We are a group of enthusiastic christians that love Jesus Christ, and serve him, His majesty parish is a church subsidiary of the redeemed christian church of God.Under kaduna province 1, House of his glory zone, Almond house area.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: solomonope1 
github_username:  oluseg

# Build settings
markdown: kramdown
