# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sof.L.X
email: solomonfaith53@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site was created for graphic lovers. You can also join what we are doing here  (if you love computer graphical works) and in.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: @solomonope1 
github_username:  oluseg

# Build settings
markdown: kramdown
